name: Code Format Check

on:
  pull_request:
    branches:
      - main # our default branch

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier check
        run: npx prettier . --check
